version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php56
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - fei-unison-sync:/home:nocopy
  php56:
    container_name: php56
    build:
      context: ./php56
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ../dms-merrin5/:/var/www/dms-merrin5
      - fei-unison-sync:/home:nocopy
    expose:
      - "9000"
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.1
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: "root"
    command: ['mysqld', '--character-set-server=utf8mb4']

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
        - "1025:1025"
        - "1080:1080"

  parsoid:
    container_name: parsoid
    image: benhutchins/parsoid
    ports:
        - "8142:8142"
        - "8000:8000"

volumes:
  mysql-data:

  fei-unison-sync:
    external: true